<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT math (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | maths | french)*>
<!ELEMENT evaluation (#PCDATA)> ]>

<entities>
    <math>
        <expression>20 &lt; 50</expression>
        <evaluation>true</evaluation>
    </math>
    <french>Il nous &#xE9;tait tr&#xE8;s agr&#xE9;able d&apos;aprendre que vous avez les numismatiques, mais il nous fachait bien de en m&#xEA;me temps, que vous n&apos;en possedez pas une &#xE9;preuve. </french>
</entities>
