<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT math (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | math | french)*>
<!ELEMENT evaluation (#PCDATA)> ]>

<entities>
    <math>
        <expression>20&lt;50</expression>
        <evaluation>true</evaluation>
    </math>
    <french>Il nous était très agréable d'aprendre que vous avez les numismatiques, mais il nous fachait bien de en même temps, que vous n'en possedez pas une épreuve. </french>
</entities>
